markdown: kramdown
permalink: /:categories/:title

# main text of home
name: Saeed Varasteh Yazdi
bio: Assistant Professor, Machine Learning Engineer

# twitter summary info
# description: A blog about technology and stuff related

# if it's an external image, update below for true
# better with square images
external-image: false
picture: assets/images/saeed_avatar.png

# If you want to include your resume, set to true
# and specify source (external or local).
resume: false
resume-external: false
resume-url: assets/CV.pdf

url: https://varasteh.info/ # http://saeedvarasteh.github.io
# your url: http://USERNAME.github.io

# To enable google analytics, supply your token below
#analytics-google: 'UA-87996300-2'

# if you don't want comments in your posts, leave categories empty
disqus:
  shortname: saeedvarasteh # enter this from your disqus account
  categories: [blog, lecture] # only show disqus for posts that have these categories

# if you don't have any of social below, comment the line
# facebook: myfacebook
twitter: saeedvarasteh
#linkedin: saeedvarasteh
github: saeedvarasteh
email: saeed.varasteh@imag.com

authors:
    saeed:
        name: Saeed Varasteh Yazdi
        bio: Assistant Professor, Machine Learning Engineer
        external-image: false
        picture: assets/images/saeed_avatar.png
        twitter: saeedvarasteh

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: large

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

# if you don't need "about" or "blog", comment them out below
about: true
blog: true
lectures: true

# do you want to show the "read time" of the posts?
read-time: false

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# Display links for next and previous posts for the specified categories
post-advance-links: [blog]

# show author block at the end of a post ?
show-author: true

# do you want some animations?
animation: true

plugins:
  - jekyll-seo-tag
